default_agent: illuminate_writer_dev
agents:
  illuminate_writer_dev:
    name: illuminate_writer_dev
    language: python
    node_version: '20'
    entrypoint: /Users/scott.hurrey/local/illuminate-conversational-intelligence/agents/writer/a2a_server.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/scott.hurrey/local/illuminate-conversational-intelligence/agents/writer
    aws:
      execution_role: arn:aws:iam::856599266077:role/illuminate-agent-role-dev
      execution_role_auto_create: true
      account: '856599266077'
      region: us-east-1
      ecr_repository: 856599266077.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-illuminate_writer_dev
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: illuminate_writer_dev-JzvuLl48Pd
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:856599266077:runtime/illuminate_writer_dev-JzvuLl48Pd
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-illuminate_writer_dev-builder
      execution_role: arn:aws:iam::856599266077:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-af37903ce0
      source_bucket: bedrock-agentcore-codebuild-sources-856599266077-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: illuminate_writer_dev_mem-9AfLyd7bvT
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:856599266077:memory/illuminate_writer_dev_mem-9AfLyd7bvT
      memory_name: illuminate_writer_dev_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
