default_agent: illuminate_writer_dev
agents:
  illuminate_writer_dev:
    name: illuminate_writer_dev
    language: python
    node_version: '20'
    entrypoint: /Users/shurrey/local/test-bb-data/agents/writer/a2a_server.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/shurrey/local/test-bb-data/agents/writer
    aws:
      execution_role: arn:aws:iam::442606396405:role/illuminate-agent-role-dev
      execution_role_auto_create: true
      account: '442606396405'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-442606396405-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: A2A
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: illuminate_writer_dev-3qYW7DGUyR
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:442606396405:runtime/illuminate_writer_dev-3qYW7DGUyR
      agent_session_id: 064924e6-ab49-49b4-8663-f48158f98771
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: illuminate_writer_dev_mem-NM6jkw7BWf
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:442606396405:memory/illuminate_writer_dev_mem-NM6jkw7BWf
      memory_name: illuminate_writer_dev_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
